import { options } from "@/app/api/auth/[...nextauth]/options";
import Navbar from "@/components/Navbar";

import type { Metadata } from "next";

import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Kinect Portal - My Games",
  description: "Generated by create next app",
};

export default async function MyGamesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  if (!session) {
    redirect("/login");
  }
  return (
    <>
      <div>
        <Navbar />
      </div>
      {children}
    </>
  );
}
