import { options } from "@/app/api/auth/[...nextauth]/options";

import type { Metadata } from "next";

import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Kinect Portal - Login",
  description: "Generated by create next app",
};

export default async function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  if (session) {
    redirect("/home");
  }
  return <>{children}</>;
}
